version: "3.8"
services:
  backend:
    restart: always
    container_name: backend
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file: ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
  frontend:
    restart: always
    container_name: frontend
    command: npm start
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  nginx:
    restart: always
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"